# $Id: Makefile.nt,v 1.1 2000-07-13 08:56:48 alik Exp $

include ../../env_inc.nt.mak

default: performance

include mkperformance.nt.mak

clean:
        @if exist *.obj $(RM) *.obj
        @if exist *.lib $(RM) *.lib
        @if exist *.exe $(RM) *.exe

