# $Id: Makefile.nt,v 1.2 2003-03-13 13:30:14 rssh Exp $

include ../../env_inc.nt.mak
include ../../config/ORB_description.nt.mak
include ../../config/env_common.nt.mak

default: SQLTool

include mkSQLTool.nt.mak

clean:
        @if exist *.obj $(RM) *.obj
        @if exist *.lib $(RM) *.lib
        @if exist *.exe $(RM) *.exe

