
COSQUERY_NUMERIC_OBJS=\
 $(COSQUERY_NUMERIC_DIR)/NumericImpl.o\
 $(COSQUERY_NUMERIC_DIR)/NumericParser.o

$(COSQUERY_NUMERIC_OBJS): $(COSQUERY_NUMERIC_DIR)/%.o: $(COSQUERY_NUMERIC_DIR)/%.cpp
	$(CXXLIBCOMPILE) -o $@ -c $<
