
COSQUERY_INTERBASE_OBJS=\
 $(COSQUERY_INTERBASE_DIR)/IBHandlers.o\
 $(COSQUERY_INTERBASE_DIR)/InterBaseConnectionManager.o\
 $(COSQUERY_INTERBASE_DIR)/InterBaseDBFormatHandler.o\
 $(COSQUERY_INTERBASE_DIR)/InterBaseQuery.o\
 $(COSQUERY_INTERBASE_DIR)/InterBaseQueryManager.o\
 $(COSQUERY_INTERBASE_DIR)/InterBaseQueryResource.o\
 $(COSQUERY_INTERBASE_DIR)/InterBaseLobs.o\
 $(COSQUERY_INTERBASE_DIR)/IBTransSet.o

$(COSQUERY_INTERBASE_OBJS): $(COSQUERY_INTERBASE_DIR)/%.o: $(COSQUERY_INTERBASE_DIR)/%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@
clean:
	-rm -f $(COSQUERY_INTERBASE_OBJS)

