# Part of  Grad-Soft Query Service.
# (C) Grad-Soft Ltd, Kiev, Ukraine
# http://www.gradsoft.kiev.ua
# $Id: Makefile.nt,v 1.5 2003-03-13 13:30:05 rssh Exp $

include ../../env_inc.nt.mak
include ../../config/ORB_description.nt.mak     
include ../../config/env_common.nt.mak


SUBDIRS=QueryGrammar

default: build

include mkUtils.nt.mak
include QueryGrammar/mkQueryGrammar.nt.mak


default-build: build
build-client: build

build: $(CosQuery_Utils_OBJS) build-obj

build-obj:
	@for %i in ($(SUBDIRS)) do @cd $(PROJECT_ROOT)\src\Utils\%i && $(MAKE) /F Makefile.nt build


clean:
	@if exist *.obj $(RM) *.obj
	@for %i in ($(SUBDIRS)) do @cd $(PROJECT_ROOT)\src\Utils\%i && $(MAKE) /F Makefile.nt clean

