# $Id: Makefile.nt,v 1.2 2003-03-13 13:30:12 rssh Exp $

include ../../env_inc.nt.mak
include ../../config/ORB_description.nt.mak
include ../../config/env_common.nt.mak

default: DBFReader

include mkDBFReader.nt.mak

clean:
        @if exist *.obj $(RM) *.obj
        @if exist *.lib $(RM) *.lib
        @if exist *.exe $(RM) *.exe

