

CSTEP4_DIR=$(project_root)/c4
CSTEP4_SRC=$(CSTEP4_DIR)/c4.cpp
CSTEP4_OBJ=$(CSTEP4_DIR)/c4.o
CSTEP4_OBJS=$(CSTEP4_DIR)/c4.o
CSTEP4_EXE=$(CSTEP4_DIR)/c4
STEPC4=$(CSTEP4_EXE)

$(CSTEP4_OBJ): $(CSTEP4_SRC)
	$(CXXCOMPILE) -I../../src -I../../src/include -o $(CSTEP4_OBJ) -c $(CSTEP4_SRC)

$(STEPC4): $(CSTEP4_OBJS)
	$(CXXCOMPILE) -o $(STEPC4) $(CSTEP4_OBJS) -L../../src $(UAKGQUERY_CL_LIB) $(LIBS)

